spring.application.name=Financialrisk
# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/Finacialriskdetection
spring.datasource.username=postgres
spring.datasource.password=123456

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# risk thresholds
risk.threshold.medium=10000
risk.threshold.high=50000

# Disable default Spring Security UserDetailsService (we use JWT)
spring.security.user.name=disabled
spring.security.user.password=disabled